version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    networks:
      - db-app
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      # APP_DB_USER: app_db
      # APP_DB_PASS: app_db
      # APP_DB_NAME: app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 45s
      interval: 60s
      retries: 10
    restart: always

  backend:
    container_name: backend
    #build: .
    image: vkv0220/flask:2.0
    networks:
      - db-app
    environment:
      API_KEY: ${API_KEY}
      NAME: ${NAME}
      FLASK_APP: "hello.py"
      # DBPASSWORD: postgres
      # DBUSER: postgres
      # DB: postgres
      # DBHOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    # command: ["./wait-for-postgres.sh", "db", "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

networks:
  db-app:
    driver: bridge
